<?php
/**
 * Indus Grammar School ERP - Database Backup & Restore Panel
 * Version 4.0.0
 */

$pageTitle = 'Backup & Restore';
$breadcrumbActive = 'Administration';
include_once __DIR__ . '/../../includes/header.php';
AuthMiddleware::requirePermission('system_settings');

$db = Database::getConnection();

// Fetch previous backups registered in database
$backups = [];
try {
    $backups = $db->query("
        SELECT bh.*, u.username as creator_name 
        FROM backup_history bh 
        LEFT JOIN users u ON bh.created_by = u.id 
        ORDER BY bh.created_at DESC
    ")->fetchAll();
} catch (Exception $e) {
    error_log("Error loading backups list: " . $e->getMessage());
}
?>

<div class="row mb-4 align-items-center">
    <div class="col-sm-6">
        <h3 class="fw-bold text-secondary mb-0"><i class="fa-solid fa-database me-2 text-primary"></i>Backup & Restore</h3>
        <p class="text-muted small mb-0">Generate database backups, download SQL archives, or restore the ERP database state from past snapshots.</p>
    </div>
    <div class="col-sm-6 text-sm-end mt-3 mt-sm-0">
        <button class="btn btn-primary px-4" id="btnBackupNow">
            <i class="fa-solid fa-file-export me-2"></i>Create SQL Backup
        </button>
    </div>
</div>

<div class="row g-4">
    <!-- Backup History Table -->
    <div class="col-lg-12">
        <div class="custom-table-card shadow-sm border-0">
            <div class="p-4 border-bottom">
                <h5 class="fw-bold mb-0 text-secondary">Historical System Snapshots</h5>
            </div>
            
            <div class="table-responsive">
                <table class="table custom-table table-hover align-middle mb-0">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Backup File Name</th>
                            <th>Export Date</th>
                            <th>File Size</th>
                            <th>Generated By</th>
                            <th class="text-end">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if (empty($backups)): ?>
                            <tr><td colspan="6" class="text-center py-5 text-muted">No database snapshots generated yet.</td></tr>
                        <?php else: foreach ($backups as $b): ?>
                            <tr>
                                <td>#<?php echo $b['id']; ?></td>
                                <td class="fw-bold text-dark"><?php echo sanitize($b['backup_name']); ?></td>
                                <td>
                                    <div><?php echo date('d M Y', strtotime($b['created_at'])); ?></div>
                                    <small class="text-muted" style="font-size:0.75rem;"><?php echo date('h:i A', strtotime($b['created_at'])); ?></small>
                                </td>
                                <td><span class="badge bg-light text-dark border"><?php echo number_format($b['size_kb'], 2); ?> KB</span></td>
                                <td><code><?php echo sanitize($b['creator_name'] ?: 'System'); ?></code></td>
                                <td class="text-end">
                                    <a href="../../ajax/admin.php?action=download_backup&id=<?php echo $b['id']; ?>" class="btn btn-sm btn-outline-primary me-1" title="Download SQL File">
                                        <i class="fa-solid fa-download"></i> Download
                                    </a>
                                    <button class="btn btn-sm btn-outline-warning btn-restore-backup me-1" data-id="<?php echo $b['id']; ?>" title="Restore Snapshot">
                                        <i class="fa-solid fa-clock-rotate-left"></i> Restore
                                    </button>
                                    <button class="btn btn-sm btn-outline-danger btn-delete-backup" data-id="<?php echo $b['id']; ?>" title="Delete Backup">
                                        <i class="fa-solid fa-trash-can"></i>
                                    </button>
                                </td>
                            </tr>
                        <?php endforeach; endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Toast Feedback -->
<div class="position-fixed bottom-0 end-0 p-3" style="z-index:9999;">
    <div id="bkpToast" class="toast align-items-center text-white border-0" role="alert">
        <div class="d-flex">
            <div class="toast-body fw-semibold" id="bkpToastMsg"></div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"></button>
        </div>
    </div>
</div>

<!-- Backdrop Loading Spinner Overlay -->
<div id="loadingOverlay" class="d-none position-fixed top-0 start-0 w-100 h-100 bg-dark bg-opacity-50 align-items-center justify-content-center" style="z-index: 10000;">
    <div class="bg-white p-4 rounded-3 text-center shadow-lg border">
        <div class="spinner-border text-primary mb-2" role="status"></div>
        <div class="fw-bold text-secondary" id="loadingMsg">Executing process, please wait...</div>
    </div>
</div>

<?php $extraJS = '<script>
function showToast(msg, ok) {
    const t = document.getElementById("bkpToast");
    const m = document.getElementById("bkpToastMsg");
    t.classList.remove("bg-success","bg-danger");
    t.classList.add(ok ? "bg-success" : "bg-danger");
    m.textContent = msg;
    new bootstrap.Toast(t).show();
}

function showLoading(show, msg = "Processing...") {
    const loader = document.getElementById("loadingOverlay");
    const label = document.getElementById("loadingMsg");
    if (show) {
        label.textContent = msg;
        loader.classList.remove("d-none");
        loader.classList.add("d-flex");
    } else {
        loader.classList.remove("d-flex");
        loader.classList.add("d-none");
    }
}

document.addEventListener("DOMContentLoaded", function() {
    
    // Create Backup Action
    const btnBackup = document.getElementById("btnBackupNow");
    if (btnBackup) {
        btnBackup.addEventListener("click", function() {
            showLoading(true, "Generating SQL schema and data export dump...");
            const fd = new FormData();
            fd.append("action", "create_backup");
            fd.append("csrf_token", "' . csrfToken() . '");
            
            fetch("../../ajax/admin.php", { method: "POST", body: fd })
                .then(r => r.json())
                .then(data => {
                    showLoading(false);
                    showToast(data.message, data.success);
                    if (data.success) setTimeout(() => location.reload(), 1000);
                })
                .catch(() => { showLoading(false); showToast("Network communication error.", false); });
        });
    }

    // Delete Backup
    document.querySelectorAll(".btn-delete-backup").forEach(btn => {
        btn.addEventListener("click", function() {
            const id = this.dataset.id;
            if(!confirm("Are you sure you want to permanently delete this backup archive from storage? This cannot be undone.")) return;
            
            showLoading(true, "Removing snapshot backup file...");
            const fd = new FormData();
            fd.append("action", "delete_backup");
            fd.append("csrf_token", "' . csrfToken() . '");
            fd.append("id", id);
            
            fetch("../../ajax/admin.php", { method: "POST", body: fd })
                .then(r => r.json())
                .then(data => {
                    showLoading(false);
                    showToast(data.message, data.success);
                    if (data.success) setTimeout(() => location.reload(), 1000);
                })
                .catch(() => { showLoading(false); showToast("Network error.", false); });
        });
    });

    // Restore Backup
    document.querySelectorAll(".btn-restore-backup").forEach(btn => {
        btn.addEventListener("click", function() {
            const id = this.dataset.id;
            if(!confirm("WARNING: Restoring the database will overwrite all current tables, students, marks, registers, and transactions with the selected snapshot. Are you sure you want to proceed?")) return;
            
            showLoading(true, "Restoring database state... Please do not close this window.");
            const fd = new FormData();
            fd.append("action", "restore_backup");
            fd.append("csrf_token", "' . csrfToken() . '");
            fd.append("id", id);
            
            fetch("../../ajax/admin.php", { method: "POST", body: fd })
                .then(r => r.json())
                .then(data => {
                    showLoading(false);
                    showToast(data.message, data.success);
                    if (data.success) setTimeout(() => {
                        // Redirect to dashboard on successful restore to ensure correct sessions
                        window.location.href = "dashboard.php";
                    }, 2000);
                })
                .catch(() => { showLoading(false); showToast("Network error during restoration.", false); });
        });
    });
});
</script>';
include_once __DIR__ . '/../../includes/footer.php'; ?>
